<?php

// autoload_classmap.php @generated by TYPO3

$typo3InstallDir = \TYPO3\CMS\Core\Core\Environment::getPublicPath() . '/';

return array(
    'Bithost\\Pdfviewhelpers\\' => array($typo3InstallDir . 'typo3conf/ext/pdfviewhelpers/Classes'),
    'DanLundgren\\DlQrcodesgenerator\\' => array($typo3InstallDir . 'typo3conf/ext/dl_qrcodesgenerator/Classes'),
    'EBT\\ExtensionBuilder\\' => array($typo3InstallDir . 'typo3conf/ext/extension_builder/Classes'),
    'FluidTYPO3\\Vhs\\' => array($typo3InstallDir . 'typo3conf/ext/vhs/Classes'),
    'GridElementsTeam\\Gridelements\\' => array($typo3InstallDir . 'typo3conf/ext/gridelements/Classes'),
);
