<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "dl_iponlyestate"
 *
 * Auto generated by Extension Builder 2020-04-22
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Iponly Estate',
	'description' => 'IPO-QRService',
	'category' => 'plugin',
	'author' => 'Dan Lundgren',
	'author_email' => 'danlundgren0@gmail.com',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-7.6.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);